language: python

python:
  - "2.7"

dist: trusty

install:
  - pip install --upgrade pip
  - pip install --upgrade -r requirements.txt
  - pip install -e .
  - parserator train training/labeled.xml,training/ledcor_addresses.xml usaddress

script:
  - nosetests --with-coverage --cover-package=usaddress
